name: Docker Image CI
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build ./PregnaCare --file ./PregnaCare/Dockerfile --tag 21anhn/swp-backend:latest
      
      - name: Push Docker image to Docker Hub
        run: docker push 21anhn/swp-backend:latest
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/swp391
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker system prune -a -f
